version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.0
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          executor: cypress/base-12-16-1
      - cypress/run:
          requires:
            - cypress/install
          executor: cypress/base-12-16-1
          # https://github.com/cypress-io/circleci-orb/issues/299
          command: apt-get update && apt-get install -y libgbm-dev && yarn ci:serve-and-test
          no-workspace: true
          record: true
          parallel: true
          parallelism: 4
          store_artifacts: true
          post-steps:
            - run: yarn test:unit
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            - run: ./node_modules/.bin/nyc report
            # send coverage to Codecov
            - run: ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/codecov --pipe
